version: '3.4'

services:
  basketapi:
    image: ${DOCKER_REGISTRY-}sampleecommercebasketapi
    build:
      context: .
      dockerfile: SampleEcommerce.BasketApi/Dockerfile
    ports:
      - 9393:80
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

