version: '3.4'

services:
  sampleecommerce.basketapi:
    image: ${DOCKER_REGISTRY-}sampleecommercebasketapi
    build:
      context: .
      dockerfile: SampleEcommerce.BasketApi/Dockerfile

  sampleecommerce.productapi:
    image: ${DOCKER_REGISTRY-}sampleecommerceproductapi
    build:
      context: .
      dockerfile: SampleEcommerce.ProductApi/Dockerfile

